// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design internal header
// See Vcv32e40x_gvsoc_core_lint_top.h for the primary calling header

#ifndef VERILATED_VCV32E40X_GVSOC_CORE_LINT_TOP___024ROOT_H_
#define VERILATED_VCV32E40X_GVSOC_CORE_LINT_TOP___024ROOT_H_  // guard

#include "verilated.h"
class Vcv32e40x_gvsoc_core_lint_top_cv32e40x_if_c_obi;
class Vcv32e40x_gvsoc_core_lint_top_cv32e40x_if_c_obi__Tz3_TBz4;


class Vcv32e40x_gvsoc_core_lint_top__Syms;

class alignas(VL_CACHE_LINE_BYTES) Vcv32e40x_gvsoc_core_lint_top___024root final : public VerilatedModule {
  public:
    // CELLS
    Vcv32e40x_gvsoc_core_lint_top_cv32e40x_if_c_obi* __PVT__cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__m_c_obi_instr_if;
    Vcv32e40x_gvsoc_core_lint_top_cv32e40x_if_c_obi__Tz3_TBz4* __PVT__cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__m_c_obi_data_if;

    // DESIGN SPECIFIC STATE
    // Anonymous structures to workaround compiler member-count bugs
    struct {
        VL_IN8(clk_i,0,0);
        VL_IN8(rst_ni,0,0);
        CData/*0:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__clk;
        VL_OUT8(instr_req_o,0,0);
        VL_IN8(instr_gnt_i,0,0);
        VL_IN8(instr_rvalid_i,0,0);
        VL_IN8(instr_err_i,0,0);
        VL_OUT8(data_req_o,0,0);
        VL_IN8(data_gnt_i,0,0);
        VL_IN8(data_rvalid_i,0,0);
        VL_OUT8(data_be_o,3,0);
        VL_OUT8(data_we_o,0,0);
        VL_IN8(data_err_i,0,0);
        VL_IN8(data_exokay_i,0,0);
        VL_IN8(fetch_enable_i,0,0);
        VL_OUT8(core_sleep_o,0,0);
        VL_OUT8(fencei_flush_req_o,0,0);
        VL_IN8(fencei_flush_ack_i,0,0);
        VL_OUT8(debug_havereset_o,0,0);
        VL_OUT8(debug_running_o,0,0);
        VL_OUT8(debug_halted_o,0,0);
        VL_OUT8(debug_pc_valid_o,0,0);
        CData/*0:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__lsu_busy;
        CData/*0:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__lsu_interruptible;
        CData/*0:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__last_op_if;
        CData/*0:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__last_op_id;
        CData/*0:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__last_op_ex;
        CData/*0:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__abort_op_if;
        CData/*0:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__abort_op_id;
        CData/*0:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__abort_op_wb;
        CData/*0:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__csr_counter_read;
        CData/*0:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__csr_wr_in_wb_flush;
        CData/*0:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__lsu_split_ex;
        CData/*1:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__lsu_err_wb;
        CData/*0:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__lsu_valid_ex;
        CData/*0:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__lsu_valid_1;
        CData/*1:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__mpu_status_wb;
        CData/*1:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__align_status_wb;
        CData/*0:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__id_ready;
        CData/*0:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__ex_ready;
        CData/*0:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__wb_ready;
        CData/*0:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__if_valid;
        CData/*0:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__id_valid;
        CData/*0:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__ex_valid;
        CData/*0:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__wb_valid;
        CData/*0:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__alu_jmp_id;
        CData/*0:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__alu_en_id;
        CData/*0:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__sys_en_id;
        CData/*0:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__sys_mret_insn_id;
        CData/*0:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__csr_illegal;
        CData/*0:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__xif_csr_error_ex;
        CData/*0:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__irq_req_ctrl;
        CData/*0:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__irq_wu_ctrl;
        CData/*4:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT____Vcellout__gen_basic_interrupt__DOT__int_controller_i__irq_id_ctrl_o;
        CData/*0:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__sleep_unit_i__DOT__fetch_enable_q;
        CData/*0:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__sleep_unit_i__DOT__fetch_enable_d;
        CData/*0:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__sleep_unit_i__DOT__core_busy_q;
        CData/*0:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__sleep_unit_i__DOT__core_clock_gate_i__DOT__en_latch;
        CData/*0:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__if_stage_i__DOT__prefetch_valid;
        CData/*0:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__if_stage_i__DOT__prefetch_ready;
        CData/*0:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__if_stage_i__DOT__illegal_c_insn;
        CData/*0:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__if_stage_i__DOT__instr_compressed;
        CData/*0:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__if_stage_i__DOT__prefetch_resp_valid;
        CData/*0:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__if_stage_i__DOT__prefetch_trans_valid;
    };
    struct {
        CData/*0:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__if_stage_i__DOT__prefetch_trans_ready;
        CData/*0:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__if_stage_i__DOT__seq_valid;
        CData/*0:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__if_stage_i__DOT__seq_last;
        CData/*0:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__if_stage_i__DOT__seq_tbljmp;
        CData/*0:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__if_stage_i__DOT__seq_pushpop;
        CData/*4:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__if_stage_i__DOT__instr_meta_n;
        CData/*0:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__if_stage_i__DOT__prefetch_unit_i__DOT__fetch_ready;
        CData/*0:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__if_stage_i__DOT__prefetch_unit_i__DOT__fetch_ptr_resp;
        CData/*1:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__if_stage_i__DOT__prefetch_unit_i__DOT__fetch_priv_lvl_resp;
        CData/*0:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__if_stage_i__DOT__prefetch_unit_i__DOT__prefetcher_i__DOT__state_q;
        CData/*0:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__if_stage_i__DOT__prefetch_unit_i__DOT__prefetcher_i__DOT__next_state;
        CData/*0:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__if_stage_i__DOT__prefetch_unit_i__DOT__prefetcher_i__DOT__trans_ptr_access_q;
        CData/*1:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__if_stage_i__DOT__prefetch_unit_i__DOT__prefetcher_i__DOT__trans_priv_lvl_q;
        CData/*2:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__if_stage_i__DOT__prefetch_unit_i__DOT__alignment_buffer_i__DOT__instr_cnt_n;
        CData/*2:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__if_stage_i__DOT__prefetch_unit_i__DOT__alignment_buffer_i__DOT__instr_cnt_q;
        CData/*1:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__if_stage_i__DOT__prefetch_unit_i__DOT__alignment_buffer_i__DOT__outstanding_cnt_n;
        CData/*1:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__if_stage_i__DOT__prefetch_unit_i__DOT__alignment_buffer_i__DOT__outstanding_cnt_q;
        CData/*0:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__if_stage_i__DOT__prefetch_unit_i__DOT__alignment_buffer_i__DOT__pop_q;
        CData/*0:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__if_stage_i__DOT__prefetch_unit_i__DOT__alignment_buffer_i__DOT__aligned_n;
        CData/*0:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__if_stage_i__DOT__prefetch_unit_i__DOT__alignment_buffer_i__DOT__aligned_q;
        CData/*0:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__if_stage_i__DOT__prefetch_unit_i__DOT__alignment_buffer_i__DOT__complete_n;
        CData/*0:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__if_stage_i__DOT__prefetch_unit_i__DOT__alignment_buffer_i__DOT__complete_q;
        CData/*1:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__if_stage_i__DOT__prefetch_unit_i__DOT__alignment_buffer_i__DOT__n_flush_n;
        CData/*1:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__if_stage_i__DOT__prefetch_unit_i__DOT__alignment_buffer_i__DOT__n_flush_q;
        CData/*0:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__if_stage_i__DOT__prefetch_unit_i__DOT__alignment_buffer_i__DOT__resp_valid_gated;
        CData/*1:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__if_stage_i__DOT__prefetch_unit_i__DOT__alignment_buffer_i__DOT__instr_priv_lvl_q;
        CData/*0:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__if_stage_i__DOT__prefetch_unit_i__DOT__alignment_buffer_i__DOT__is_clic_ptr_q;
        CData/*0:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__if_stage_i__DOT__prefetch_unit_i__DOT__alignment_buffer_i__DOT__is_mret_ptr_q;
        CData/*0:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__if_stage_i__DOT__prefetch_unit_i__DOT__alignment_buffer_i__DOT__is_tbljmp_ptr_q;
        CData/*0:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__if_stage_i__DOT__prefetch_unit_i__DOT__alignment_buffer_i__DOT__ptr_fetch_accepted_q;
        CData/*2:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__if_stage_i__DOT__prefetch_unit_i__DOT__alignment_buffer_i__DOT__valid_n;
        CData/*2:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__if_stage_i__DOT__prefetch_unit_i__DOT__alignment_buffer_i__DOT__valid_int;
        CData/*2:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__if_stage_i__DOT__prefetch_unit_i__DOT__alignment_buffer_i__DOT__valid_q;
        CData/*1:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__if_stage_i__DOT__prefetch_unit_i__DOT__alignment_buffer_i__DOT__rptr;
        CData/*1:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__if_stage_i__DOT__prefetch_unit_i__DOT__alignment_buffer_i__DOT__rptr_n;
        CData/*1:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__if_stage_i__DOT__prefetch_unit_i__DOT__alignment_buffer_i__DOT__rptr2;
        CData/*1:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__if_stage_i__DOT__prefetch_unit_i__DOT__alignment_buffer_i__DOT__wptr;
        CData/*1:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__if_stage_i__DOT__prefetch_unit_i__DOT__alignment_buffer_i__DOT__wptr_n;
        CData/*0:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__if_stage_i__DOT__prefetch_unit_i__DOT__alignment_buffer_i__DOT__valid;
        CData/*0:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__if_stage_i__DOT__prefetch_unit_i__DOT__alignment_buffer_i__DOT__aligned_is_compressed;
        CData/*0:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__if_stage_i__DOT__prefetch_unit_i__DOT__alignment_buffer_i__DOT__unaligned_is_compressed;
        CData/*0:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__if_stage_i__DOT__prefetch_unit_i__DOT__alignment_buffer_i__DOT____Vlvbound_h0f2080d3__0;
        CData/*0:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__if_stage_i__DOT__prefetch_unit_i__DOT__alignment_buffer_i__DOT____Vlvbound_h29d26df9__0;
        CData/*0:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__if_stage_i__DOT__prefetch_unit_i__DOT__alignment_buffer_i__DOT____VdfgExtracted_ha053764d__0;
        CData/*0:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__if_stage_i__DOT__prefetch_unit_i__DOT__alignment_buffer_i__DOT____VdfgRegularize_h16c80b4c_4_0;
        CData/*0:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__if_stage_i__DOT__prefetch_unit_i__DOT__alignment_buffer_i__DOT____VdfgRegularize_h16c80b4c_4_4;
        CData/*0:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__if_stage_i__DOT__mpu_i__DOT__pma_err;
        CData/*2:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__if_stage_i__DOT__mpu_i__DOT__state_q;
        CData/*2:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__if_stage_i__DOT__mpu_i__DOT__state_n;
        CData/*0:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__if_stage_i__DOT__instruction_obi_i__DOT__state_q;
        CData/*0:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__if_stage_i__DOT__instruction_obi_i__DOT__next_state;
        CData/*3:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__if_stage_i__DOT__gen_seq__DOT__sequencer_i__DOT__instr_cnt_q;
        CData/*3:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__if_stage_i__DOT__gen_seq__DOT__sequencer_i__DOT__seq_instr;
        CData/*0:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__if_stage_i__DOT__gen_seq__DOT__sequencer_i__DOT__seq_load;
        CData/*0:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__if_stage_i__DOT__gen_seq__DOT__sequencer_i__DOT__seq_store;
        CData/*0:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__if_stage_i__DOT__gen_seq__DOT__sequencer_i__DOT__seq_move_a2s;
        CData/*0:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__if_stage_i__DOT__gen_seq__DOT__sequencer_i__DOT__seq_move_s2a;
        CData/*3:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__if_stage_i__DOT__gen_seq__DOT__sequencer_i__DOT__seq_state_n;
        CData/*3:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__if_stage_i__DOT__gen_seq__DOT__sequencer_i__DOT__seq_state_q;
        CData/*0:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__if_stage_i__DOT__gen_seq__DOT__sequencer_i__DOT__seq_first_fsm;
        CData/*0:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__if_stage_i__DOT__gen_seq__DOT__sequencer_i__DOT__ready_fsm;
        CData/*0:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__id_stage_i__DOT__mul_en;
        CData/*0:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__id_stage_i__DOT__div_en;
        CData/*0:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__id_stage_i__DOT__lsu_en;
    };
    struct {
        CData/*0:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__id_stage_i__DOT__csr_en;
        CData/*1:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__id_stage_i__DOT__bch_jmp_mux_sel;
        CData/*0:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__ex_stage_i__DOT__instr_valid;
        CData/*0:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__ex_stage_i__DOT__mul_ready;
        CData/*0:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__ex_stage_i__DOT__mul_valid;
        CData/*0:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__ex_stage_i__DOT__div_ready;
        CData/*0:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__ex_stage_i__DOT__div_valid;
        CData/*0:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__ex_stage_i__DOT__alu_cmp_result;
        CData/*0:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__ex_stage_i__DOT__div_en;
        CData/*5:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__ex_stage_i__DOT__div_clz_result;
        CData/*0:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__ex_stage_i__DOT__mul_en;
        CData/*0:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__ex_stage_i__DOT__csr_is_illegal;
        CData/*0:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__ex_stage_i__DOT____VdfgRegularize_h221eb34c_0_6;
        CData/*0:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__ex_stage_i__DOT__alu_i__DOT____VdfgExtracted_h4f034531__0;
        VlWide<5>/*159:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__ex_stage_i__DOT__alu_i__DOT__ff_one_i__DOT__index_nodes;
        VlWide<6>/*191:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__ex_stage_i__DOT__alu_i__DOT__alu_b_cpop_i__DOT__sum;
        CData/*0:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__ex_stage_i__DOT__div__DOT__div_i__DOT__div_rem_d;
        CData/*0:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__ex_stage_i__DOT__div__DOT__div_i__DOT__div_rem_q;
        CData/*0:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__ex_stage_i__DOT__div__DOT__div_i__DOT__comp_inv_d;
        CData/*0:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__ex_stage_i__DOT__div__DOT__div_i__DOT__comp_inv_q;
        CData/*0:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__ex_stage_i__DOT__div__DOT__div_i__DOT__res_inv_d;
        CData/*0:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__ex_stage_i__DOT__div__DOT__div_i__DOT__res_inv_q;
        CData/*5:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__ex_stage_i__DOT__div__DOT__div_i__DOT__cnt_q;
        CData/*5:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__ex_stage_i__DOT__div__DOT__div_i__DOT__cnt_d;
        CData/*0:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__ex_stage_i__DOT__div__DOT__div_i__DOT__init_dummy_cnt;
        CData/*0:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__ex_stage_i__DOT__div__DOT__div_i__DOT__divisor_en;
        CData/*0:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__ex_stage_i__DOT__div__DOT__div_i__DOT__comp_out;
        CData/*0:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__ex_stage_i__DOT__div__DOT__div_i__DOT__init_en;
        CData/*1:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__ex_stage_i__DOT__div__DOT__div_i__DOT__next_state;
        CData/*1:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__ex_stage_i__DOT__div__DOT__div_i__DOT__state;
        CData/*0:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__ex_stage_i__DOT__div__DOT__div_i__DOT__div_rem;
        CData/*0:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__ex_stage_i__DOT__div__DOT__div_i__DOT__op_b_is_neg;
        CData/*0:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__ex_stage_i__DOT__div__DOT__div_i__DOT____VdfgRegularize_h6404b41a_0_3;
        CData/*1:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__ex_stage_i__DOT__mul__DOT__mult_i__DOT__mulh_state;
        CData/*1:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__ex_stage_i__DOT__mul__DOT__mult_i__DOT__mulh_state_next;
        CData/*0:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__load_store_unit_i__DOT__trans_valid;
        CData/*0:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__load_store_unit_i__DOT__mpu_trans_valid;
        CData/*0:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__load_store_unit_i__DOT__wpt_resp_valid;
        CData/*0:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__load_store_unit_i__DOT__buffer_trans_valid;
        CData/*0:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__load_store_unit_i__DOT__buffer_trans_ready;
        CData/*0:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__load_store_unit_i__DOT__filter_trans_valid;
        CData/*0:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__load_store_unit_i__DOT__filter_trans_ready;
        CData/*0:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__load_store_unit_i__DOT__filter_resp_valid;
        CData/*0:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__load_store_unit_i__DOT__bus_trans_valid;
        CData/*1:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__load_store_unit_i__DOT__cnt_q;
        CData/*1:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__load_store_unit_i__DOT__next_cnt;
        CData/*0:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__load_store_unit_i__DOT__count_up;
        CData/*0:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__load_store_unit_i__DOT__ctrl_update;
        CData/*1:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__load_store_unit_i__DOT__lsu_size_q;
        CData/*0:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__load_store_unit_i__DOT__lsu_sext_q;
        CData/*0:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__load_store_unit_i__DOT__lsu_we_q;
        CData/*1:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__load_store_unit_i__DOT__rdata_offset_q;
        CData/*3:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__load_store_unit_i__DOT__be;
        CData/*0:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__load_store_unit_i__DOT__split_q;
        CData/*0:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__load_store_unit_i__DOT__misaligned_access;
        CData/*0:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__load_store_unit_i__DOT__modified_access;
        CData/*0:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__load_store_unit_i__DOT__done_0;
        CData/*0:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__load_store_unit_i__DOT__trans_valid_q;
        CData/*0:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__load_store_unit_i__DOT____VdfgRegularize_h39df9a1d_1_1;
        CData/*0:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__load_store_unit_i__DOT__mpu_i__DOT__pma_err;
        CData/*0:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__load_store_unit_i__DOT__mpu_i__DOT__mpu_block_core;
        CData/*0:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__load_store_unit_i__DOT__mpu_i__DOT__mpu_err_trans_valid;
        CData/*0:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__load_store_unit_i__DOT__mpu_i__DOT__mpu_err_trans_ready;
        CData/*2:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__load_store_unit_i__DOT__mpu_i__DOT__state_q;
    };
    struct {
        CData/*2:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__load_store_unit_i__DOT__mpu_i__DOT__state_n;
        CData/*0:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__load_store_unit_i__DOT__align_check_i__DOT__align_block_core;
        CData/*0:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__load_store_unit_i__DOT__align_check_i__DOT__align_trans_valid;
        CData/*0:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__load_store_unit_i__DOT__align_check_i__DOT__align_trans_ready;
        CData/*2:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__load_store_unit_i__DOT__align_check_i__DOT__state_q;
        CData/*2:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__load_store_unit_i__DOT__align_check_i__DOT__state_n;
        CData/*1:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__load_store_unit_i__DOT__response_filter_i__DOT__bus_cnt_q;
        CData/*1:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__load_store_unit_i__DOT__response_filter_i__DOT__bus_next_cnt;
        CData/*1:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__load_store_unit_i__DOT__response_filter_i__DOT__core_cnt_q;
        CData/*1:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__load_store_unit_i__DOT__response_filter_i__DOT__core_next_cnt;
        CData/*5:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__load_store_unit_i__DOT__response_filter_i__DOT__outstanding_q;
        CData/*5:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__load_store_unit_i__DOT__response_filter_i__DOT__outstanding_next;
        CData/*0:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__load_store_unit_i__DOT__write_buffer_i__DOT__state;
        CData/*0:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__load_store_unit_i__DOT__write_buffer_i__DOT__next_state;
        CData/*0:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__load_store_unit_i__DOT__write_buffer_i__DOT__push;
        CData/*0:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__load_store_unit_i__DOT__gen_wpt__DOT__wpt_i__DOT__wpt_block_core;
        CData/*0:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__load_store_unit_i__DOT__gen_wpt__DOT__wpt_i__DOT__wpt_trans_valid;
        CData/*0:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__load_store_unit_i__DOT__gen_wpt__DOT__wpt_i__DOT__wpt_trans_ready;
        CData/*1:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__load_store_unit_i__DOT__gen_wpt__DOT__wpt_i__DOT__state_q;
        CData/*1:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__load_store_unit_i__DOT__gen_wpt__DOT__wpt_i__DOT__state_n;
        CData/*0:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__wb_stage_i__DOT__instr_valid;
        CData/*0:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__wb_stage_i__DOT__lsu_exception;
        CData/*0:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__wb_stage_i__DOT__xif_waiting;
        CData/*1:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__wb_stage_i__DOT__lsu_mpu_status_q;
        CData/*1:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__wb_stage_i__DOT__lsu_align_status_q;
        CData/*0:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__wb_stage_i__DOT__lsu_valid_q;
        CData/*0:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__wb_stage_i__DOT__lsu_valid;
        CData/*0:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__wb_stage_i__DOT____VdfgRegularize_h5fe00629_0_5;
        CData/*0:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__cs_registers_i__DOT__csr_we_int;
        CData/*0:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__cs_registers_i__DOT__mepc_we;
        CData/*0:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__cs_registers_i__DOT__tselect_we;
        CData/*0:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__cs_registers_i__DOT__dcsr_we;
        CData/*0:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__cs_registers_i__DOT__dpc_we;
        CData/*0:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__cs_registers_i__DOT__dscratch0_we;
        CData/*0:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__cs_registers_i__DOT__dscratch1_we;
        CData/*0:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__cs_registers_i__DOT__mscratch_we;
        CData/*0:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__cs_registers_i__DOT__jvt_we;
        CData/*0:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__cs_registers_i__DOT__mstatus_we;
        CData/*0:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__cs_registers_i__DOT__mcause_we;
        CData/*0:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__cs_registers_i__DOT__mtvec_we;
        CData/*0:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__cs_registers_i__DOT__mie_we;
        CData/*0:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__cs_registers_i__DOT__priv_lvl_we;
        QData/*63:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__cs_registers_i__DOT__mhpmcounter_we;
        CData/*0:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__cs_registers_i__DOT____VdfgRegularize_h3edf1550_1_3;
        CData/*0:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__cs_registers_i__DOT____VdfgRegularize_h3edf1550_1_6;
        CData/*0:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__cs_registers_i__DOT____VdfgRegularize_h3edf1550_1_10;
        CData/*0:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__cs_registers_i__DOT____VdfgRegularize_h3edf1550_1_12;
        CData/*0:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__cs_registers_i__DOT____VdfgRegularize_h3edf1550_1_74;
        CData/*0:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__cs_registers_i__DOT____VdfgRegularize_h3edf1550_1_75;
        CData/*0:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__cs_registers_i__DOT____VdfgRegularize_h3edf1550_1_76;
        CData/*0:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__cs_registers_i__DOT__debug_triggers_i__DOT__gen_triggers__DOT__tdata1_we_int;
        CData/*0:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__cs_registers_i__DOT__debug_triggers_i__DOT__gen_triggers__DOT__tdata2_we_int;
        CData/*1:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__cs_registers_i__DOT__debug_triggers_i__DOT__gen_triggers__DOT__lsu_addr_low_lsb;
        CData/*1:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__cs_registers_i__DOT__debug_triggers_i__DOT__gen_triggers__DOT__lsu_addr_high_lsb;
        CData/*0:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__cs_registers_i__DOT__debug_triggers_i__DOT____VdfgRegularize_h1be56877_2_7;
        CData/*1:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__controller_i__DOT__controller_fsm_i__DOT__ctrl_fsm_cs;
        CData/*1:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__controller_i__DOT__controller_fsm_i__DOT__ctrl_fsm_ns;
        CData/*2:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__controller_i__DOT__controller_fsm_i__DOT__debug_fsm_cs;
        CData/*2:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__controller_i__DOT__controller_fsm_i__DOT__debug_fsm_ns;
        CData/*0:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__controller_i__DOT__controller_fsm_i__DOT__nmi_pending_q;
        CData/*0:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__controller_i__DOT__controller_fsm_i__DOT__nmi_is_store_q;
        CData/*0:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__controller_i__DOT__controller_fsm_i__DOT__debug_mode_n;
        CData/*0:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__controller_i__DOT__controller_fsm_i__DOT__debug_mode_q;
        CData/*0:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__controller_i__DOT__controller_fsm_i__DOT__single_step_halt_if_n;
    };
    struct {
        CData/*0:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__controller_i__DOT__controller_fsm_i__DOT__single_step_halt_if_q;
        CData/*0:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__controller_i__DOT__controller_fsm_i__DOT__sys_mret_id;
        CData/*0:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__controller_i__DOT__controller_fsm_i__DOT__jmp_id;
        CData/*0:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__controller_i__DOT__controller_fsm_i__DOT__jump_taken_id;
        CData/*0:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__controller_i__DOT__controller_fsm_i__DOT__clic_ptr_in_id;
        CData/*0:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__controller_i__DOT__controller_fsm_i__DOT__branch_taken_ex;
        CData/*0:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__controller_i__DOT__controller_fsm_i__DOT__branch_taken_n;
        CData/*0:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__controller_i__DOT__controller_fsm_i__DOT__branch_taken_q;
        CData/*0:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__controller_i__DOT__controller_fsm_i__DOT__exception_in_wb;
        CData/*0:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__controller_i__DOT__controller_fsm_i__DOT__fencei_in_wb;
        CData/*0:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__controller_i__DOT__controller_fsm_i__DOT__dret_in_wb;
        CData/*0:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__controller_i__DOT__controller_fsm_i__DOT__ebreak_in_wb;
        CData/*0:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__controller_i__DOT__controller_fsm_i__DOT__trigger_match_in_wb;
        CData/*0:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__controller_i__DOT__controller_fsm_i__DOT__etrigger_in_wb;
        CData/*0:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__controller_i__DOT__controller_fsm_i__DOT__pending_nmi_early;
        CData/*0:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__controller_i__DOT__controller_fsm_i__DOT__pending_async_debug;
        CData/*0:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__controller_i__DOT__controller_fsm_i__DOT__pending_sync_debug;
        CData/*0:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__controller_i__DOT__controller_fsm_i__DOT__debug_interruptible;
        CData/*2:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__controller_i__DOT__controller_fsm_i__DOT__debug_cause_n;
        CData/*2:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__controller_i__DOT__controller_fsm_i__DOT__debug_cause_q;
        CData/*0:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__controller_i__DOT__controller_fsm_i__DOT__woke_to_debug_q;
        CData/*0:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__controller_i__DOT__controller_fsm_i__DOT__woke_to_interrupt_q;
        CData/*0:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__controller_i__DOT__controller_fsm_i__DOT__fence_req_set;
        CData/*0:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__controller_i__DOT__controller_fsm_i__DOT__fence_req_clr;
        CData/*0:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__controller_i__DOT__controller_fsm_i__DOT__fence_req_q;
        CData/*0:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__controller_i__DOT__controller_fsm_i__DOT__fencei_req_and_ack_q;
        CData/*0:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__controller_i__DOT__controller_fsm_i__DOT__wb_counter_event;
        CData/*0:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__controller_i__DOT__controller_fsm_i__DOT__wb_counter_event_gated;
        CData/*0:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__controller_i__DOT__controller_fsm_i__DOT__csr_flush_ack_n;
        CData/*0:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__controller_i__DOT__controller_fsm_i__DOT__csr_flush_ack_q;
        CData/*0:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__controller_i__DOT__controller_fsm_i__DOT__sequence_in_progress_wb;
        CData/*0:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__controller_i__DOT__controller_fsm_i__DOT__sequence_in_progress_id;
        CData/*0:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__controller_i__DOT__controller_fsm_i__DOT__id_stage_haltable;
        CData/*0:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__controller_i__DOT__controller_fsm_i__DOT__interrupt_blanking_q;
        CData/*0:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__controller_i__DOT__controller_fsm_i__DOT__clic_ptr_in_progress_id;
        CData/*0:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__controller_i__DOT__controller_fsm_i__DOT__clic_ptr_in_progress_id_clear;
        CData/*0:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__controller_i__DOT__controller_fsm_i__DOT____VdfgExtracted_ha7292f8a__0;
        CData/*0:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__controller_i__DOT__controller_fsm_i__DOT____VdfgExtracted_ha9ecc2ef__0;
        CData/*0:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__controller_i__DOT__controller_fsm_i__DOT____VdfgExtracted_h225c6b2f__0;
        CData/*0:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__controller_i__DOT__controller_fsm_i__DOT____VdfgExtracted_h7c88e781__0;
        CData/*0:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__controller_i__DOT__controller_fsm_i__DOT____VdfgExtracted_h7e4cdf56__0;
        CData/*0:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__controller_i__DOT__controller_fsm_i__DOT____VdfgExtracted_hebfcbc4a__0;
        CData/*0:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__controller_i__DOT__controller_fsm_i__DOT____VdfgExtracted_h161e6967__0;
        CData/*0:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__controller_i__DOT__controller_fsm_i__DOT____VdfgExtracted_h9c43ac38__0;
        CData/*0:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__controller_i__DOT__controller_fsm_i__DOT____VdfgRegularize_ha32e4db6_0_11;
        CData/*0:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__controller_i__DOT__controller_fsm_i__DOT____VdfgRegularize_ha32e4db6_0_12;
        CData/*0:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__controller_i__DOT__controller_fsm_i__DOT____VdfgRegularize_ha32e4db6_0_18;
        CData/*0:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__controller_i__DOT__controller_fsm_i__DOT____VdfgRegularize_ha32e4db6_0_19;
        CData/*0:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__controller_i__DOT__controller_fsm_i__DOT____VdfgRegularize_ha32e4db6_0_21;
        CData/*0:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__controller_i__DOT__controller_fsm_i__DOT____VdfgRegularize_ha32e4db6_0_22;
        CData/*0:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__controller_i__DOT__controller_fsm_i__DOT____VdfgRegularize_ha32e4db6_0_23;
        CData/*0:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__controller_i__DOT__controller_fsm_i__DOT____VdfgRegularize_ha32e4db6_0_25;
        CData/*0:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__controller_i__DOT__controller_fsm_i__DOT____VdfgRegularize_ha32e4db6_0_26;
        CData/*1:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__controller_i__DOT__bypass_i__DOT__rf_rd_ex_match;
        CData/*0:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__controller_i__DOT__bypass_i__DOT__rf_rd_ex_jalr_match;
        CData/*1:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__controller_i__DOT__bypass_i__DOT__rf_rd_wb_match;
        CData/*0:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__controller_i__DOT__bypass_i__DOT__rf_rd_wb_jalr_match;
        CData/*0:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__controller_i__DOT__bypass_i__DOT__csr_write_in_wb;
        CData/*0:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__controller_i__DOT__bypass_i__DOT__csr_impl_write_in_wb;
        CData/*0:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__controller_i__DOT__bypass_i__DOT__rf_we_ex;
        CData/*0:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__controller_i__DOT__bypass_i__DOT__rf_we_wb;
        CData/*0:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__controller_i__DOT__bypass_i__DOT__lsu_en_wb;
        CData/*0:0*/ __VdfgRegularize_hd87f99a1_1_5;
        CData/*0:0*/ __VdfgRegularize_hd87f99a1_1_6;
    };
    struct {
        CData/*0:0*/ __VdfgRegularize_hd87f99a1_1_9;
        CData/*3:0*/ __Vfunc_get_stack_adj_base__0__rlist;
        CData/*3:0*/ __Vfunc_pushpop_reg_length__1__Vfuncout;
        CData/*3:0*/ __Vfunc_pushpop_reg_length__1__rlist4;
        CData/*4:0*/ __Vfunc_sn_to_regnum__2__Vfuncout;
        CData/*4:0*/ __Vfunc_sn_to_regnum__2__snum;
        CData/*4:0*/ __Vfunc_sn_to_regnum__3__Vfuncout;
        CData/*4:0*/ __Vfunc_sn_to_regnum__3__snum;
        CData/*4:0*/ __Vfunc_sn_to_regnum__4__Vfuncout;
        CData/*4:0*/ __Vfunc_sn_to_regnum__4__snum;
        CData/*4:0*/ __Vfunc_sn_to_regnum__5__Vfuncout;
        CData/*4:0*/ __Vfunc_sn_to_regnum__5__snum;
        CData/*4:0*/ __Vfunc_sn_to_regnum__6__Vfuncout;
        CData/*4:0*/ __Vfunc_sn_to_regnum__6__snum;
        CData/*4:0*/ __Vfunc_sn_to_regnum__7__Vfuncout;
        CData/*4:0*/ __Vfunc_sn_to_regnum__7__snum;
        CData/*4:0*/ __Vfunc_sn_to_regnum__8__Vfuncout;
        CData/*4:0*/ __Vfunc_sn_to_regnum__8__snum;
        CData/*4:0*/ __Vfunc_sn_to_regnum__9__Vfuncout;
        CData/*4:0*/ __Vfunc_sn_to_regnum__9__snum;
        CData/*4:0*/ __Vfunc_sn_to_regnum__10__Vfuncout;
        CData/*4:0*/ __Vfunc_sn_to_regnum__10__snum;
        CData/*4:0*/ __Vfunc_sn_to_regnum__11__Vfuncout;
        CData/*4:0*/ __Vfunc_sn_to_regnum__11__snum;
        CData/*1:0*/ __Vfunc_mtvec_mode_clint_resolve__25__Vfuncout;
        CData/*1:0*/ __Vfunc_mtvec_mode_clint_resolve__25__current_value;
        CData/*1:0*/ __Vfunc_mtvec_mode_clint_resolve__25__next_value;
        CData/*3:0*/ __Vfunc_mcontrol2_6_match_resolve__29__Vfuncout;
        CData/*3:0*/ __Vfunc_mcontrol2_6_match_resolve__29__next_value;
        CData/*3:0*/ __Vfunc_mcontrol2_6_match_resolve__32__Vfuncout;
        CData/*3:0*/ __Vfunc_mcontrol2_6_match_resolve__32__next_value;
        CData/*0:0*/ __Vtrigprevexpr___TOP__cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__load_store_unit_i__DOT__bus_trans_valid__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__id_ready__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__wb_ready__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__controller_i__DOT__controller_fsm_i__DOT____VdfgExtracted_ha7292f8a__0__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__load_store_unit_i__DOT__wpt_resp_valid__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__controller_i__DOT__controller_fsm_i__DOT__exception_in_wb__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__if_stage_i__DOT__prefetch_resp_valid__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__if_stage_i__DOT__prefetch_unit_i__DOT__fetch_ready__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__controller_i__DOT__controller_fsm_i__DOT____VdfgExtracted_h225c6b2f__0__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__controller_i__DOT__controller_fsm_i__DOT____VdfgExtracted_h7c88e781__0__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__controller_i__DOT__controller_fsm_i__DOT__debug_interruptible__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__controller_i__DOT__controller_fsm_i__DOT__pending_sync_debug__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__controller_i__DOT__controller_fsm_i__DOT__sys_mret_id__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__controller_i__DOT__controller_fsm_i__DOT____VdfgExtracted_h9c43ac38__0__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__if_valid__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__last_op_if__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__abort_op_if__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__wb_stage_i__DOT__instr_valid__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__controller_i__DOT__controller_fsm_i__DOT____VdfgRegularize_ha32e4db6_0_22__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__ex_valid__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__controller_i__DOT__controller_fsm_i__DOT__jmp_id__0;
        VlWide<6>/*191:0*/ __Vtrigprevexpr___TOP__cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__ex_stage_i__DOT__alu_i__DOT__alu_b_cpop_i__DOT__sum__0;
        CData/*1:0*/ __Vtrigprevexpr___TOP__cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__controller_i__DOT__bypass_i__DOT__rf_rd_ex_match__0;
        CData/*1:0*/ __Vtrigprevexpr___TOP__cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__controller_i__DOT__bypass_i__DOT__rf_rd_wb_match__0;
        CData/*3:0*/ __Vtrigprevexpr___TOP__cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__load_store_unit_i__DOT__be__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__load_store_unit_i__DOT__count_up__0;
        CData/*1:0*/ __Vtrigprevexpr___TOP__cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__mpu_status_wb__0;
        CData/*1:0*/ __Vtrigprevexpr___TOP__cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__align_status_wb__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__controller_i__DOT__controller_fsm_i__DOT____VdfgRegularize_ha32e4db6_0_26__0;
        VlWide<5>/*159:0*/ __Vtrigprevexpr___TOP__cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__ex_stage_i__DOT__alu_i__DOT__ff_one_i__DOT__index_nodes__0;
        CData/*0:0*/ __VstlDidInit;
        CData/*0:0*/ __VstlFirstIteration;
        CData/*0:0*/ __Vtrigprevexpr___TOP__cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__load_store_unit_i__DOT__bus_trans_valid__1;
    };
    struct {
        CData/*0:0*/ __Vtrigprevexpr___TOP__cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__id_ready__1;
        CData/*0:0*/ __Vtrigprevexpr___TOP__cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__controller_i__DOT__controller_fsm_i__DOT____VdfgExtracted_ha7292f8a__0__1;
        CData/*0:0*/ __Vtrigprevexpr___TOP__cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__controller_i__DOT__controller_fsm_i__DOT____VdfgExtracted_h225c6b2f__0__1;
        CData/*0:0*/ __Vtrigprevexpr___TOP__cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__controller_i__DOT__controller_fsm_i__DOT____VdfgExtracted_h7c88e781__0__1;
        CData/*0:0*/ __Vtrigprevexpr___TOP__cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__controller_i__DOT__controller_fsm_i__DOT__exception_in_wb__1;
        CData/*0:0*/ __Vtrigprevexpr___TOP__cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__controller_i__DOT__controller_fsm_i__DOT__debug_interruptible__1;
        CData/*0:0*/ __Vtrigprevexpr___TOP__cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__controller_i__DOT__controller_fsm_i__DOT__pending_sync_debug__1;
        CData/*0:0*/ __Vtrigprevexpr___TOP__cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__controller_i__DOT__controller_fsm_i__DOT__sys_mret_id__1;
        CData/*0:0*/ __Vtrigprevexpr___TOP__cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__controller_i__DOT__controller_fsm_i__DOT____VdfgExtracted_h9c43ac38__0__1;
        CData/*0:0*/ __Vtrigprevexpr___TOP__cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__if_valid__1;
        CData/*0:0*/ __Vtrigprevexpr___TOP__cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__last_op_if__1;
        CData/*0:0*/ __Vtrigprevexpr___TOP__cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__abort_op_if__1;
        CData/*0:0*/ __VicoDidInit;
        CData/*0:0*/ __VicoFirstIteration;
        CData/*0:0*/ __Vtrigprevexpr___TOP__cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__load_store_unit_i__DOT__bus_trans_valid__2;
        CData/*0:0*/ __Vtrigprevexpr___TOP__cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__id_ready__2;
        CData/*0:0*/ __Vtrigprevexpr___TOP__cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__wb_ready__1;
        CData/*0:0*/ __Vtrigprevexpr___TOP__cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__controller_i__DOT__controller_fsm_i__DOT____VdfgExtracted_ha7292f8a__0__2;
        CData/*0:0*/ __Vtrigprevexpr___TOP__cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__load_store_unit_i__DOT__wpt_resp_valid__1;
        CData/*0:0*/ __Vtrigprevexpr___TOP__cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__controller_i__DOT__controller_fsm_i__DOT__exception_in_wb__2;
        CData/*0:0*/ __Vtrigprevexpr___TOP__cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__if_stage_i__DOT__prefetch_resp_valid__1;
        CData/*0:0*/ __Vtrigprevexpr___TOP__cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__if_stage_i__DOT__prefetch_unit_i__DOT__fetch_ready__1;
        CData/*0:0*/ __Vtrigprevexpr___TOP__cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__controller_i__DOT__controller_fsm_i__DOT____VdfgExtracted_h225c6b2f__0__2;
        CData/*0:0*/ __Vtrigprevexpr___TOP__cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__controller_i__DOT__controller_fsm_i__DOT____VdfgExtracted_h7c88e781__0__2;
        CData/*0:0*/ __Vtrigprevexpr___TOP__cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__controller_i__DOT__controller_fsm_i__DOT__debug_interruptible__2;
        CData/*0:0*/ __Vtrigprevexpr___TOP__cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__controller_i__DOT__controller_fsm_i__DOT__pending_sync_debug__2;
        CData/*0:0*/ __Vtrigprevexpr___TOP__cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__controller_i__DOT__controller_fsm_i__DOT__sys_mret_id__2;
        CData/*0:0*/ __Vtrigprevexpr___TOP__cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__controller_i__DOT__controller_fsm_i__DOT____VdfgExtracted_h9c43ac38__0__2;
        CData/*0:0*/ __Vtrigprevexpr___TOP__cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__if_valid__2;
        CData/*0:0*/ __Vtrigprevexpr___TOP__cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__last_op_if__2;
        CData/*0:0*/ __Vtrigprevexpr___TOP__cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__abort_op_if__2;
        CData/*0:0*/ __Vtrigprevexpr___TOP__cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__wb_stage_i__DOT__instr_valid__1;
        CData/*0:0*/ __Vtrigprevexpr___TOP__cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__controller_i__DOT__controller_fsm_i__DOT____VdfgRegularize_ha32e4db6_0_22__1;
        CData/*0:0*/ __Vtrigprevexpr___TOP__cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__ex_valid__1;
        CData/*0:0*/ __Vtrigprevexpr___TOP__cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__controller_i__DOT__controller_fsm_i__DOT__jmp_id__1;
        VlWide<6>/*191:0*/ __Vtrigprevexpr___TOP__cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__ex_stage_i__DOT__alu_i__DOT__alu_b_cpop_i__DOT__sum__1;
        CData/*1:0*/ __Vtrigprevexpr___TOP__cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__controller_i__DOT__bypass_i__DOT__rf_rd_ex_match__1;
        CData/*1:0*/ __Vtrigprevexpr___TOP__cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__controller_i__DOT__bypass_i__DOT__rf_rd_wb_match__1;
        CData/*3:0*/ __Vtrigprevexpr___TOP__cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__load_store_unit_i__DOT__be__1;
        CData/*0:0*/ __Vtrigprevexpr___TOP__cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__load_store_unit_i__DOT__count_up__1;
        CData/*1:0*/ __Vtrigprevexpr___TOP__cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__mpu_status_wb__1;
        CData/*1:0*/ __Vtrigprevexpr___TOP__cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__align_status_wb__1;
        CData/*0:0*/ __Vtrigprevexpr___TOP__cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__controller_i__DOT__controller_fsm_i__DOT____VdfgRegularize_ha32e4db6_0_26__1;
        VlWide<5>/*159:0*/ __Vtrigprevexpr___TOP__cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__ex_stage_i__DOT__alu_i__DOT__ff_one_i__DOT__index_nodes__1;
        CData/*0:0*/ __Vtrigprevexpr___TOP__clk_i__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__rst_ni__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__clk__0;
        CData/*0:0*/ __VactDidInit;
        CData/*0:0*/ __VactContinue;
        SData/*11:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__cs_registers_i__DOT__csr_raddr;
        SData/*15:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__cs_registers_i__DOT__hpm_events;
        SData/*15:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__cs_registers_i__DOT__hpm_events_raw;
        SData/*10:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__controller_i__DOT__controller_fsm_i__DOT__exception_cause_wb;
        SData/*11:0*/ __Vfunc_get_stack_adj_base__0__Vfuncout;
        VL_IN(boot_addr_i,31,0);
        VL_OUT(instr_addr_o,31,0);
        VL_IN(instr_rdata_i,31,0);
        VL_OUT(data_addr_o,31,0);
        VL_OUT(data_wdata_o,31,0);
        VL_IN(data_rdata_i,31,0);
        VL_IN(irq_i,31,0);
        VL_OUT(debug_pc_o,31,0);
        IData/*17:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__ctrl_byp;
        IData/*31:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__rf_wdata_wb;
    };
    struct {
        IData/*31:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__rf_wdata_ex;
        IData/*27:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__csr_hz;
        IData/*31:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__wpt_match_wb;
        IData/*31:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__dcsr;
        IData/*31:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__trigger_match_ex;
        IData/*31:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__if_stage_i__DOT__branch_addr_n;
        IData/*31:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__if_stage_i__DOT__prefetch_trans_addr;
        IData/*31:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__if_stage_i__DOT__prefetch_unit_i__DOT__prefetcher_i__DOT__trans_addr_q;
        IData/*31:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__if_stage_i__DOT__prefetch_unit_i__DOT__alignment_buffer_i__DOT__addr_n;
        IData/*31:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__if_stage_i__DOT__prefetch_unit_i__DOT__alignment_buffer_i__DOT__addr_q;
        IData/*31:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__if_stage_i__DOT__prefetch_unit_i__DOT__alignment_buffer_i__DOT__instr;
        IData/*31:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__if_stage_i__DOT__prefetch_unit_i__DOT__alignment_buffer_i__DOT____VdfgRegularize_h16c80b4c_0_0;
        IData/*31:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__if_stage_i__DOT__gen_seq__DOT__sequencer_i__DOT____VdfgExtracted_ha5d9f9b3__0;
        IData/*31:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__if_stage_i__DOT__gen_seq__DOT__sequencer_i__DOT____VdfgExtracted_h61fde1fa__0;
        IData/*31:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__if_stage_i__DOT__gen_seq__DOT__sequencer_i__DOT____VdfgExtracted_h9cad3cb4__0;
        IData/*31:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__if_stage_i__DOT__gen_seq__DOT__sequencer_i__DOT____VdfgExtracted_h8eb8e2d3__0;
        IData/*31:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__id_stage_i__DOT__operand_a_fw;
        IData/*31:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__id_stage_i__DOT__operand_b_fw;
        IData/*31:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__id_stage_i__DOT__imm_i_type;
        IData/*31:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__id_stage_i__DOT__cv32e40x_pc_target_i__DOT__pc_target;
        IData/*31:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__ex_stage_i__DOT__alu_result;
        IData/*31:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__ex_stage_i__DOT__alu_i__DOT__adder_result;
        IData/*31:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__ex_stage_i__DOT__alu_i__DOT__shifter_bb;
        IData/*31:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__ex_stage_i__DOT__alu_i__DOT__result_shnadd;
        IData/*31:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__ex_stage_i__DOT__alu_i__DOT__min_minu_result;
        IData/*31:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__ex_stage_i__DOT__alu_i__DOT__max_maxu_result;
        IData/*31:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__ex_stage_i__DOT__alu_i__DOT__clz_data_in;
        IData/*31:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__ex_stage_i__DOT__alu_i__DOT__ff_one_i__DOT__sel_nodes;
        IData/*31:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__ex_stage_i__DOT__div__DOT__div_i__DOT__quotient_q;
        IData/*31:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__ex_stage_i__DOT__div__DOT__div_i__DOT__quotient_d;
        IData/*31:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__ex_stage_i__DOT__div__DOT__div_i__DOT__remainder_q;
        IData/*31:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__ex_stage_i__DOT__div__DOT__div_i__DOT__remainder_d;
        IData/*31:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__ex_stage_i__DOT__div__DOT__div_i__DOT__divisor_q;
        IData/*31:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__ex_stage_i__DOT__div__DOT__div_i__DOT__divisor_d;
        IData/*31:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__ex_stage_i__DOT__div__DOT__div_i__DOT__res_mux;
        IData/*16:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__ex_stage_i__DOT__mul__DOT__mult_i__DOT__mulh_ah;
        IData/*16:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__ex_stage_i__DOT__mul__DOT__mult_i__DOT__mulh_bh;
        IData/*31:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__load_store_unit_i__DOT__rdata_q;
        IData/*31:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__load_store_unit_i__DOT__rdata_ext;
        IData/*31:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__load_store_unit_i__DOT__gen_wpt__DOT__wpt_i__DOT__wpt_match_n;
        IData/*31:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__load_store_unit_i__DOT__gen_wpt__DOT__wpt_i__DOT__wpt_match_q;
        IData/*31:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__wb_stage_i__DOT__lsu_wpt_match_q;
        IData/*31:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__cs_registers_i__DOT__csr_wdata_int;
        IData/*31:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__cs_registers_i__DOT__csr_rdata_int;
        IData/*31:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__cs_registers_i__DOT__mepc_n;
        IData/*31:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__cs_registers_i__DOT__tdata1_rdata;
        IData/*31:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__cs_registers_i__DOT__tdata2_rdata;
        IData/*31:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__cs_registers_i__DOT__dcsr_n;
        IData/*31:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__cs_registers_i__DOT__dpc_n;
        IData/*31:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__cs_registers_i__DOT__dscratch0_n;
        IData/*31:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__cs_registers_i__DOT__dscratch1_n;
        IData/*31:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__cs_registers_i__DOT__mscratch_n;
        IData/*31:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__cs_registers_i__DOT__jvt_n;
        IData/*31:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__cs_registers_i__DOT__mstatus_n;
        IData/*31:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__cs_registers_i__DOT__mcause_n;
        IData/*31:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__cs_registers_i__DOT__mtvec_n;
        IData/*31:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__cs_registers_i__DOT__mie_n;
        VlWide<32>/*1023:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__cs_registers_i__DOT__mhpmevent_q;
        VlWide<32>/*1023:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__cs_registers_i__DOT__mhpmevent_n;
        IData/*31:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__cs_registers_i__DOT__mcountinhibit_q;
        IData/*31:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__cs_registers_i__DOT__mcountinhibit_n;
        IData/*31:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__cs_registers_i__DOT__mhpmcounter_write_lower;
        IData/*31:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__cs_registers_i__DOT__mhpmcounter_write_upper;
        IData/*31:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__cs_registers_i__DOT__jvt_csr_i__DOT__rdata_q;
    };
    struct {
        IData/*31:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__cs_registers_i__DOT__mepc_csr_i__DOT__rdata_q;
        IData/*31:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__cs_registers_i__DOT__mscratch_csr_i__DOT__rdata_q;
        IData/*31:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__cs_registers_i__DOT__mstatus_csr_i__DOT__rdata_q;
        IData/*31:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__cs_registers_i__DOT__debug_triggers_i__DOT__tselect_n;
        IData/*31:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__cs_registers_i__DOT__debug_triggers_i__DOT__tdata2_n;
        IData/*31:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__cs_registers_i__DOT__debug_triggers_i__DOT__gen_triggers__DOT__tmatch_csr__BRA__0__KET____DOT__tdata1_csr_i__DOT__rdata_q;
        IData/*31:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__cs_registers_i__DOT__debug_triggers_i__DOT__gen_triggers__DOT__tmatch_csr__BRA__0__KET____DOT__tdata2_csr_i__DOT__rdata_q;
        IData/*31:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__cs_registers_i__DOT__debug_triggers_i__DOT__gen_triggers__DOT__tselect_csr_i__DOT__rdata_q;
        IData/*31:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__cs_registers_i__DOT__gen_debug_csr__DOT__dscratch0_csr_i__DOT__rdata_q;
        IData/*31:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__cs_registers_i__DOT__gen_debug_csr__DOT__dscratch1_csr_i__DOT__rdata_q;
        IData/*31:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__cs_registers_i__DOT__gen_debug_csr__DOT__dcsr_csr_i__DOT__rdata_q;
        IData/*31:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__cs_registers_i__DOT__gen_debug_csr__DOT__dpc_csr_i__DOT__rdata_q;
        IData/*31:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__cs_registers_i__DOT__basic_mode_csrs__DOT__mcause_csr_i__DOT__rdata_q;
        IData/*31:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__cs_registers_i__DOT__basic_mode_csrs__DOT__mtvec_csr_i__DOT__rdata_q;
        IData/*31:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__cs_registers_i__DOT__basic_mode_csrs__DOT__mie_csr_i__DOT__rdata_q;
        IData/*31:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__gen_basic_interrupt__DOT__int_controller_i__DOT__irq_q;
        IData/*31:0*/ __Vtrigprevexpr___TOP__cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__dcsr__0;
        IData/*17:0*/ __Vtrigprevexpr___TOP__cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__ctrl_byp__0;
        IData/*31:0*/ __Vtrigprevexpr___TOP__cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__ex_stage_i__DOT__alu_i__DOT__ff_one_i__DOT__sel_nodes__0;
        IData/*17:0*/ __Vtrigprevexpr___TOP__cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__ctrl_byp__1;
        IData/*31:0*/ __Vtrigprevexpr___TOP__cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__dcsr__1;
        IData/*31:0*/ __Vtrigprevexpr___TOP__cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__dcsr__2;
        IData/*17:0*/ __Vtrigprevexpr___TOP__cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__ctrl_byp__2;
        IData/*31:0*/ __Vtrigprevexpr___TOP__cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__ex_stage_i__DOT__alu_i__DOT__ff_one_i__DOT__sel_nodes__1;
        IData/*31:0*/ __VactIterCount;
        VL_OUT64(mcycle_o,63,0);
        VL_IN64(time_i,63,0);
        VlWide<12>/*352:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__id_ex_pipe;
        VlWide<8>/*247:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__ex_wb_pipe;
        VlWide<6>/*190:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__if_id_pipe;
        VlWide<7>/*200:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__ctrl_fsm;
        QData/*34:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__if_stage_i__DOT__prefetch_instr;
        QData/*34:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__if_stage_i__DOT__instr_decompressed;
        QData/*34:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__if_stage_i__DOT__prefetch_inst_resp;
        QData/*34:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__if_stage_i__DOT__seq_instr;
        VlWide<4>/*104:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__if_stage_i__DOT__prefetch_unit_i__DOT__alignment_buffer_i__DOT__resp_q;
        QData/*34:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__if_stage_i__DOT__prefetch_unit_i__DOT__alignment_buffer_i__DOT__resp_n;
        QData/*34:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__if_stage_i__DOT__prefetch_unit_i__DOT__alignment_buffer_i__DOT____Vlvbound_h5834dfe2__0;
        VlWide<3>/*67:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__if_stage_i__DOT__mpu_i__DOT__pma_i__DOT__pma_cfg;
        QData/*37:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__if_stage_i__DOT__instruction_obi_i__DOT__obi_a_req_q;
        QData/*44:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__if_stage_i__DOT__gen_seq__DOT__sequencer_i__DOT__decode;
        QData/*54:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__id_stage_i__DOT__decoder_i__DOT__decoder_i_ctrl_int;
        QData/*54:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__id_stage_i__DOT__decoder_i__DOT__decoder_m_ctrl;
        QData/*54:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__id_stage_i__DOT__decoder_i__DOT__decoder_m_ctrl_int;
        QData/*54:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__id_stage_i__DOT__decoder_i__DOT__decoder_ctrl_mux;
        QData/*63:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__ex_stage_i__DOT__alu_i__DOT__shifter_tmp;
        QData/*32:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__ex_stage_i__DOT__mul__DOT__mult_i__DOT__mulh_acc;
        QData/*32:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__ex_stage_i__DOT__mul__DOT__mult_i__DOT__mulh_acc_next;
        QData/*33:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__ex_stage_i__DOT__mul__DOT__mult_i__DOT__result;
        VlWide<3>/*76:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__load_store_unit_i__DOT__trans;
        VlWide<3>/*80:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__load_store_unit_i__DOT__wpt_trans;
        VlWide<3>/*80:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__load_store_unit_i__DOT__alcheck_trans;
        VlWide<3>/*80:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__load_store_unit_i__DOT__bus_trans;
        VlWide<3>/*67:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__load_store_unit_i__DOT__mpu_i__DOT__pma_i__DOT__pma_cfg;
        VlWide<3>/*80:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__load_store_unit_i__DOT__write_buffer_i__DOT__trans_q;
        VlWide<64>/*2047:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__cs_registers_i__DOT__mhpmcounter_q;
        VlWide<64>/*2047:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__cs_registers_i__DOT__mhpmcounter_n;
        VlWide<64>/*2047:0*/ cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__cs_registers_i__DOT__mhpmcounter_increment;
        VlWide<7>/*200:0*/ __Vtrigprevexpr___TOP__cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__ctrl_fsm__0;
        QData/*44:0*/ __Vtrigprevexpr___TOP__cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__if_stage_i__DOT__gen_seq__DOT__sequencer_i__DOT__decode__0;
        VlWide<3>/*76:0*/ __Vtrigprevexpr___TOP__cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__load_store_unit_i__DOT__trans__0;
        VlWide<7>/*200:0*/ __Vtrigprevexpr___TOP__cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__ctrl_fsm__1;
        QData/*44:0*/ __Vtrigprevexpr___TOP__cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__if_stage_i__DOT__gen_seq__DOT__sequencer_i__DOT__decode__1;
        VlWide<7>/*200:0*/ __Vtrigprevexpr___TOP__cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__ctrl_fsm__2;
    };
    struct {
        QData/*44:0*/ __Vtrigprevexpr___TOP__cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__if_stage_i__DOT__gen_seq__DOT__sequencer_i__DOT__decode__2;
        VlWide<3>/*76:0*/ __Vtrigprevexpr___TOP__cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__load_store_unit_i__DOT__trans__1;
        VlUnpacked<IData/*31:0*/, 2> cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__rf_rdata_id;
        VlUnpacked<CData/*4:0*/, 1> cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__rf_waddr;
        VlUnpacked<IData/*31:0*/, 1> cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__rf_wdata;
        VlUnpacked<CData/*0:0*/, 1> cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__rf_we;
        VlUnpacked<IData/*31:0*/, 1> cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__cs_registers_i__DOT__debug_triggers_i__DOT__gen_triggers__DOT__tdata1_n;
        VlUnpacked<IData/*31:0*/, 1> cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__cs_registers_i__DOT__debug_triggers_i__DOT__gen_triggers__DOT__tdata1_rdata;
        VlUnpacked<IData/*31:0*/, 1> cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__cs_registers_i__DOT__debug_triggers_i__DOT__gen_triggers__DOT__tdata2_rdata;
        VlUnpacked<CData/*3:0*/, 1> cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__cs_registers_i__DOT__debug_triggers_i__DOT__gen_triggers__DOT__lsu_byte_addr_match;
        VlUnpacked<IData/*31:0*/, 1> cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__cs_registers_i__DOT__debug_triggers_i__DOT__gen_triggers__DOT__exception_match;
        VlUnpacked<CData/*1:0*/, 1> cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__cs_registers_i__DOT__debug_triggers_i__DOT__gen_triggers__DOT__mcontrol6_hit_resolved;
        VlUnpacked<IData/*31:0*/, 32> cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__register_file_wrapper_i__DOT__register_file_i__DOT__mem;
        VlUnpacked<IData/*31:0*/, 1> cv32e40x_gvsoc_core_lint_top__DOT__u_core__DOT__register_file_wrapper_i__DOT__register_file_i__DOT__we_dec;
    };
    VlTriggerVec<37> __VstlTriggered;
    VlTriggerVec<18> __VicoTriggered;
    VlTriggerVec<39> __VactTriggered;
    VlTriggerVec<39> __VnbaTriggered;

    // INTERNAL VARIABLES
    Vcv32e40x_gvsoc_core_lint_top__Syms* const vlSymsp;

    // CONSTRUCTORS
    Vcv32e40x_gvsoc_core_lint_top___024root(Vcv32e40x_gvsoc_core_lint_top__Syms* symsp, const char* v__name);
    ~Vcv32e40x_gvsoc_core_lint_top___024root();
    VL_UNCOPYABLE(Vcv32e40x_gvsoc_core_lint_top___024root);

    // INTERNAL METHODS
    void __Vconfigure(bool first);
};


#endif  // guard
